---
- name: Install kubeadm prerequisites
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Add pkgs.k8s.io APT signing key
  ansible.builtin.apt_key:
    url: "{{k8s_url_apt_key}}"
    keyring: "{{k8s_gpgpath}}"
    state: present

- name: Add pkgs.k8s.io APT repository
  apt_repository:
    filename: kubernetes
    repo: "deb [signed-by={{ k8s_gpgpath }}] {{ k8s_repository }} /"
    state: present

- name: Install kubeadm kubelet and kubectl
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - kubeadm
      - kubelet
      - kubectl

- name: Install calicoctl
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/calico/releases/latest/download/calicoctl-linux-amd64
    dest: /usr/bin/calicoctl
    mode: 0755

- name: Disable system swap
  shell: "swapoff -a"

- name: Remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: true
    state: present
