---
- name: Enable overlay and br_netfilter modules
  copy:
    src: modules-k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    mode: 0644

- name: Probing overlay and br_netfilter modules
  ansible.builtin.command: modprobe overlay && modprobe br_netfilter

- name: Forwarding IPv4 and letting iptables see bridged traffic
  copy:
    src: sysctl-k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    mode: 0644

- name: Apply sysctl params
  ansible.builtin.command: sysctl --system

- name: Install containerd and network tools
  ansible.builtin.apt:
    update_cache: yes
    pkg:
     - containerd.io
     - docker-buildx-plugin
     - docker-compose-plugin
     - net-tools
     - ipset

- name: Deploy default containerd config with SystemdCgroup enabled
  ansible.builtin.command: containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' | tee /etc/containerd/config.toml

- name: Restart containerd
  ansible.builtin.command: systemctl restart containerd
